#!/bin/bash

cat > Newfile <<- DELIMITER
        STUFF GOES HERE
        INCLUDE A VARIABLE $USER
        THIS IS FINE
        HEREDOCS ARE AWESOME
DELIMITER

cat > Newfile2 << DELIMITER
        STUFF GOES HERE
        INCLUDE A VARIABLE $USER
        THIS IS FINE
        HEREDOCS ARE AWESOME
DELIMITER

cat > Newfile3 << "DELIMITER"
        STUFF GOES HERE
        INCLUDE A VARIABLE $USER
        THIS IS FINE
        HEREDOCS ARE AWESOME
DELIMITER
